on:
  push:
  repository_dispatch:
    types: [trigger]

jobs:
  build-website:
    runs-on: ubuntu-lastest
    steps:
      - uses: actions/checkout@v2
      - uses: mamba-org/provision-with-micromamba@main
        with:
          enviroment-file: enviroment.yml
      - name: Conda Info
        shell: bash -l {0}
        run: |
          conda info
          conda list
          conda config --show-sources
          conda config --show
      - name: Install Nikola
      - shell: bash -l {0}
        run: |
          pip install markdown==2.6.6 nikola==7.7.12
          pip install ghp-import
      - name: Build Site
        shell: bash -l {0}
        run: nikola build
